import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Electronics",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 156,
  },
  {
    id: "2",
    name: "Fashion",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 234,
  },
  {
    id: "3",
    name: "Home & Garden",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 89,
  },
  {
    id: "4",
    name: "Sports",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 67,
  },
  {
    id: "5",
    name: "Books",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 123,
  },
  {
    id: "6",
    name: "Beauty",
    image: "/placeholder.svg?height=200&width=300",
    productCount: 78,
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description:
      "Premium noise-cancelling wireless headphones with 30-hour battery life and crystal-clear audio quality.",
    price: 199.99,
    originalPrice: 249.99,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "Electronics",
    brand: "AudioTech",
    rating: 4.8,
    reviewCount: 1247,
    inStock: true,
    tags: ["New", "Popular", "Sale"],
    colors: ["Black", "White", "Blue"],
    features: ["Noise Cancelling", "30h Battery", "Quick Charge", "Wireless"],
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Advanced fitness tracking with heart rate monitoring, GPS, and 7-day battery life.",
    price: 299.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Electronics",
    brand: "FitTech",
    rating: 4.6,
    reviewCount: 892,
    inStock: true,
    tags: ["Featured", "AI Recommended"],
    colors: ["Black", "Silver", "Rose Gold"],
    features: ["Heart Rate Monitor", "GPS", "7-day Battery", "Water Resistant"],
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Sustainable and comfortable organic cotton t-shirt in various colors and sizes.",
    price: 29.99,
    originalPrice: 39.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Fashion",
    brand: "EcoWear",
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
    tags: ["Eco-Friendly", "Sale"],
    colors: ["White", "Black", "Navy", "Gray"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    features: ["Organic Cotton", "Sustainable", "Comfortable Fit"],
  },
  {
    id: "4",
    name: "Professional Camera Lens",
    description: "85mm f/1.4 portrait lens with exceptional bokeh and sharp image quality.",
    price: 899.99,
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Electronics",
    brand: "LensMaster",
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    tags: ["Professional", "New"],
    features: ["85mm f/1.4", "Weather Sealed", "Image Stabilization"],
  },
  {
    id: "5",
    name: "Ergonomic Office Chair",
    description: "Premium ergonomic office chair with lumbar support and adjustable height.",
    price: 449.99,
    originalPrice: 599.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Home & Garden",
    brand: "ComfortSeating",
    rating: 4.7,
    reviewCount: 445,
    inStock: true,
    tags: ["Sale", "Popular"],
    colors: ["Black", "Gray", "White"],
    features: ["Lumbar Support", "Adjustable Height", "Breathable Mesh", "5-Year Warranty"],
  },
  {
    id: "6",
    name: "Yoga Mat Premium",
    description: "Non-slip premium yoga mat with alignment guides and carrying strap.",
    price: 79.99,
    images: ["/placeholder.svg?height=400&width=400"],
    category: "Sports",
    brand: "ZenFit",
    rating: 4.5,
    reviewCount: 678,
    inStock: true,
    tags: ["Popular", "Eco-Friendly"],
    colors: ["Purple", "Blue", "Green", "Pink"],
    features: ["Non-Slip", "Alignment Guides", "Eco-Friendly", "Carrying Strap"],
  },
]

export const featuredProducts = products
  .filter((p) => p.tags.includes("Featured") || p.tags.includes("Popular"))
  .slice(0, 4)
export const newProducts = products.filter((p) => p.tags.includes("New")).slice(0, 4)
export const saleProducts = products.filter((p) => p.tags.includes("Sale")).slice(0, 4)
